
language: rust
sudo: false
services:
  - docker
rust:
  - nightly

script:
  - ./misc/testsetup.sh; true
  - cargo test
  - cd libgerrit && cargo test
  - chmod 777 -R ${TRAVIS_BUILD_DIR}/target
  - docker run --rm -it -v "${TRAVIS_BUILD_DIR}":/home/rust/src silviof/rust-musl-builder:nightly cargo build -j 8 --release
  - cp ${TRAVIS_BUILD_DIR}/target/x86_64-unknown-linux-musl/release/gerrit-rust ${TRAVIS_BUILD_DIR}/gerrit-rust-${TRAVIS_COMMIT}
  - strip ${TRAVIS_BUILD_DIR}/gerrit-rust-${TRAVIS_COMMIT}

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

notifications:
  email:
    on_success: never

os:
  - linux

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OdeYlgWHHAqe7+F4BdjyfZoiCPL+bFJhvUZkh80xnyua3/ubKHvPbElvUdVA4+Yzg/NP97mlLKT/tap31m2nH+p76s9ZCPRk5hJY1h/zYAaWlpOfB2obYRohfpZJHbjkb5UhAwsjpCQfGOZwo2LmcNub6PYhqAZinwSg6iiQQYIIR471WD+XQjocNiCNf4q0ZorHpEKFc6IR3wd7r9grQo64777u/7+JWz7kJCUofv9IS8agQJXyTfz8tzLZAKwHHb5ZpeJg+0bZPc+h3YhFVKofEMEUXI+8SoVoVjDbAoGjkSWMzrfd6Fv2WY8btMxBhHV2ugzABR7+FDWilMfnkbIDV4UOf4S96lVYub6mMMMoDR/s1SSFKED8sfTzA3kCuwZRpqly00Avk2kGEQly8NYKVeelw7khoxH+eA9RPZky3JPBCasGmcvpNYXAEW78QHLSzpKd6kA45zatLAGDGYcPrSSWXUZ9bg1GRNHzm9nfIqWBk+G7YFblqrWzOeGyzG2qo5R72NLZ57OInoHN+tgnY3Idrz48+ugsGAz//7S6KaJmNfK5BEjU5P2XUjdBFiG46jZ0e8EjGzAWXq+Yfb1qizwjLHlHoe5PS01wFx9GhJtHDFSaWVg96xTzOjPG+mqpon+B3FgltDQsK8tNC/xWeYwxhYGSrjKGd7HstOQ=
  file: ${TRAVIS_BUILD_DIR}/gerrit-rust-${TRAVIS_COMMIT}
  on:
    repo: silvio/gerrit-rust
    tags: true
