
language: rust
sudo: false
rust:
  - nightly

script:
  - cargo build
  - cargo test

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

notifications:
  email:
    on_success: never

os:
  - linux
