[package]
name = "gerrit-rust"
version = "0.1.6"
authors = ["Silvio Fricke <silvio.fricke@gmail.com>"]
license = "MPL-2.0"
repository = "https://github.com/silvio/gerrit-rust"
description = "Rust client to gerrit"

[lib]
name = "gerritlib"
path = "src/gerritlib/lib.rs"

[[bin]]
name = "gerrit-rust"
path = "src/bin/gerrit-rust.rs"
doctest = true

[dependencies]
clap = "2.16.3"
curl = "0.3.8"
git2 = "0.4.4"
quick-error = "1.1.0"
regex = "0.1.80"
rustc-serialize = "0.3.19"
serde = "0.8.16"
serde_json = "0.8.3"
serde_derive = "0.8.16"
toml-config = "0.4.0"
url = "1.2.3"

[dependencies.rust-gron]
version = "*"
git = "https://github.com/silvio/rust-gron.git"
branch = "gron-via-serde"
