[package]
name = "gerrit-rust"
version = "0.1.1"
authors = ["Silvio Fricke <silvio.fricke@gmail.com>"]
license = "GPLv3"
repository = "https://github.com/silvio/gerrit-rust"
description = "Rust client to gerrit"

[lib]
name = "gerritlib"
path = "src/gerritlib/lib.rs"

[[bin]]
name = "gerrit-rust"
path = "src/bin/gerrit-rust.rs"
doctest = true

[dependencies]
clap = "2.10.0"
curl = "0.3.1"
git2 = "0.4.4"
quick-error = "1.1.0"
rustc-serialize = "0.3.19"
toml-config = "0.4.0"
url = "1.1.1"
