[package]
name = "gerrit-rust"
version = "0.1.9"
authors = ["Silvio Fricke <silvio.fricke@gmail.com>"]
license = "MPL-2.0"
repository = "https://github.com/silvio/gerrit-rust"
description = "Rust client to gerrit"

[lib]
name = "gerritlib"
path = "src/gerritlib/lib.rs"

[[bin]]
name = "gerrit-rust"
path = "src/bin/gerrit-rust.rs"
doctest = true

[dependencies]
chrono = "0.2"
clap = "2.19"
curl = ">= 0.4.4"
git2 = "0.6"
gron = "0.2"
log = "0.3"
env_logger = "0.4"
quick-error = "1.1"
regex = "0.2"
rustc-serialize = "0.3"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
toml-config = "0.4"
url = "1.3"
